
package vista;

import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author PC01
 */
public class v_menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public v_menu() {
   
     initComponents();
    }

    public JMenuItem getLink_nuevousuario() {
        return link_nuevousuario;
    }

    public JMenu getVentanaUsuario() {
        return ventanaUsuario;
    }

    public void setVentanaUsuario(JMenu ventanaUsuario) {
        this.ventanaUsuario = ventanaUsuario;
    }
    
    

    public void setLink_nuevousuario(JMenuItem link_nuevousuario) {
        this.link_nuevousuario = link_nuevousuario;
    }

    public JMenuItem getLink_rolusuario() {
        return link_rolusuario;
    }

    public void setLink_rolusuario(JMenuItem link_rolusuario) {
        this.link_rolusuario = link_rolusuario;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ventanaUsuario = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        link_nuevousuario = new javax.swing.JMenuItem();
        aaaa = new javax.swing.JMenu();
        link_rolusuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        link_salir = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("jMenu4");

        jMenu9.setText("File");
        jMenuBar2.add(jMenu9);

        jMenu11.setText("Edit");
        jMenuBar2.add(jMenu11);

        jMenu12.setText("jMenu12");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem7.setText("jMenuItem7");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ooooo.jpg"))); // NOI18N
        jLabel2.setToolTipText("");

        ventanaUsuario.setText("Usuarios");

        jMenuItem6.setText("Lista de Usuarios");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        ventanaUsuario.add(jMenuItem6);

        link_nuevousuario.setText("Nuevo usuario");
        link_nuevousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_nuevousuarioActionPerformed(evt);
            }
        });
        ventanaUsuario.add(link_nuevousuario);

        jMenuBar1.add(ventanaUsuario);

        aaaa.setText("Roles");

        link_rolusuario.setText("Roles usuarios");
        link_rolusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_rolusuarioActionPerformed(evt);
            }
        });
        aaaa.add(link_rolusuario);

        jMenuBar1.add(aaaa);

        jMenu2.setText("Proveedor");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Productos");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ventas");
        jMenuBar1.add(jMenu6);

        jMenu8.setText("Clientes");
        jMenuBar1.add(jMenu8);

        jMenu13.setText("Empleados");
        jMenuBar1.add(jMenu13);

        link_salir.setText("Salir");
        jMenuBar1.add(link_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void link_nuevousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_nuevousuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_link_nuevousuarioActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void link_rolusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_rolusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_link_rolusuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aaaa;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuItem link_nuevousuario;
    private javax.swing.JMenuItem link_rolusuario;
    private javax.swing.JMenu link_salir;
    private javax.swing.JMenu ventanaUsuario;
    // End of variables declaration//GEN-END:variables
}
